// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgrvf6MSRPYmowq3IYqUCvQZrRNVU0tTY',
    appId: '1:758455200376:web:b5b44993e8e9d715f15b8d',
    messagingSenderId: '758455200376',
    projectId: 'infinite-scroll-view',
    authDomain: 'infinite-scroll-view.firebaseapp.com',
    storageBucket: 'infinite-scroll-view.appspot.com',
    measurementId: 'G-SGPWNL5PFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNZBVdCi69vKwxnzTi3zp5Ylk-53XHd-Y',
    appId: '1:758455200376:android:a23f7ee45795c5bcf15b8d',
    messagingSenderId: '758455200376',
    projectId: 'infinite-scroll-view',
    storageBucket: 'infinite-scroll-view.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgrvf6MSRPYmowq3IYqUCvQZrRNVU0tTY',
    appId: '1:758455200376:web:fb326bfeb78ab394f15b8d',
    messagingSenderId: '758455200376',
    projectId: 'infinite-scroll-view',
    authDomain: 'infinite-scroll-view.firebaseapp.com',
    storageBucket: 'infinite-scroll-view.appspot.com',
    measurementId: 'G-7Z7SQRJCRY',
  );
}
